### ISSUE TITLE
Next link paths 404

### ISSUE THREAD

**Issue by adamschwartz** [broccolini/swiss#1]
e.g. The next link on http://broccolini.net/swiss/writing/2015/11/25/potatoes.html links to:

http://broccolini.net/writing/2016/08/06/welcome-to-jekyll.html

Instead of:

[http://broccolini.net/**swiss**/writing/2016/08/06/welcome-to-jekyll.html](http://broccolini.net/swiss/writing/2016/08/06/welcome-to-jekyll.html)

![image](https://cloud.githubusercontent.com/assets/154613/18497117/c8493148-79f9-11e6-81fa-bab2699dd278.png)

**Comment by broccolini** [comment]
Thanks for posting this issue, I noticed the problem too and pinged the Jekyll folks for advice. I'll need to make an update to build the urls with:
```
{% assign user_url = site.url | append: site.baseurl %}
{{ user_url | default: site.github.url }}
```

Will update this tomorrow.

**Comment by adamschwartz** [comment]
Happy to help!

**Comment by broccolini** [comment]
Closing this as was fixed a while back 🙃
