### ISSUE TITLE
icon-github.html not found

### ISSUE THREAD

**Issue by phocks** [broccolini/swiss#11]
I am getting this error when I try to install:

Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/Users/phocks/Sites/quoke/_includes", "/usr/local/lib/ruby/gems/2.4.0/gems/jekyll-swiss-0.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in about.md

I've tried bundle method and manual gem install method.

**Comment by phocks** [comment]
Hi there I found the problem. It is caused by the default about page installed by Jekyll. It makes reference to a file that seems to be only found in minima 

https://github.com/ezrasavard/ezora-jekyll-theme/issues/1

**Comment by broccolini** [comment]
Closing this since it's a Jekyll issue rather than an issue with this theme. Hopefully it's been fixed.
