### ISSUE TITLE
Adding image added to posts to home.html

### ISSUE THREAD

**Issue by jaythanelam** [broccolini/swiss#12]
Hi_ I'm still learning here, so I apologize for the annoying question. I'm trying to add an image added to a post show up with the post on the home page. I assume I need to add a variable or include the home.html to pull that image/url out but I'm lost on how to target it. Would you happen to know how to accomplish this (or point me in the right direction)? Any help would be greatly appreciated. Thanks!

**Comment by DirtyF** [comment]
Hi @jaythanelam,

Generally speaking, and not specifically with this theme, you can add images to a folder like `assets/images` and link to this image in your post with the markdown syntax `![alternative text](/assets/images/photo.jpg)`.

Alternately if you can use a Front Matter variable:

```yaml
---
layout: post
title: This is a post
image : /assets/images/photo.jpg
---

...
{{ page.image }}
...
```

Then You can the call the image in your post with `{{ page.image }}` (or in your layout with `{{ post.image }}`)

Hope it helps.

**Comment by jaythanelam** [comment]
never mind I was able to solve this issue

**Comment by jaythanelam** [comment]
oh, sorry! I didn't refresh the page from before. I didn't know someone had chimed in. This is such an easier solution than what I had implemented. thank you @DirtyF
