### ISSUE TITLE
Default syntax highlighting not working

### ISSUE THREAD

**Issue by melanietosik** [broccolini/swiss#13]
Thanks for a beautiful template!

I was wondering if there is a simple way to get the [default code snippet highlighting](https://jekyllrb.com/docs/templates/#code-snippet-highlighting) to work with Swiss? According to the docs, Rouge is the default highlighter in Jekyll 3+ and should just work out of the box. For example:

```
{% highlight ruby %}
def foo
  puts 'foo'
end
{% endhighlight %}
```

Default rendering:
![screen shot 2017-06-16 at 5 36 16 pm](https://user-images.githubusercontent.com/5739202/27247157-ec9bdcb2-52bb-11e7-9a82-d07532cf2115.png)

Swiss rendering:
![screen shot 2017-06-16 at 5 41 25 pm](https://user-images.githubusercontent.com/5739202/27247165-f6c8c916-52bb-11e7-882e-3b103c55c40f.png)

I tried removing/editing the CSS below from the `_components.scss` file but (expectedly) all it did was to change the color from red to black and remove the indent/blockquote.

```
// Styling markdown output

// Code formatting
pre {
    border-left: $spacer-1 solid $color-border;
    margin: $spacer-3 0;
    padding-left: 16px;
    width: (9 / 12 * 100%); // matches col-9
    overflow-x: auto;
}

code {
    color: $color-code;
    font-size: $body-font-size;
    padding: 1px 4px;
}
```

I also tried using Highlight.js, Pygments, redcarpet, etc. but couldn't get anything to work. Any thoughts on how to "override" the template CSS for `<pre>` and `<code>` tags to use the Rouge syntax highlighter instead?

Thank you!

**Comment by Bergvca** [comment]
Stumbled upon this issue after having the same problem. It can be fixed by adding the css of your favorite theme to the sass of the theme. I just copy pasted the following code:

https://gist.githubusercontent.com/vgaidarji/14ab6175b5aefd85382c965773d1dfcc/raw/c37f957fe0c111b372a2e2ac3db68110e3a12f2d/theme-son-of-obsidian.css

into the components.scss file.

**Comment by melanietosik** [comment]
I'll try that, thanks!

**Comment by DirtyF** [comment]
You can use any of the https://github.com/richleland/pygments-css styles (or create your own)

**Comment by broccolini** [comment]
Closing this as I don't believe it should be accounted for in this theme.
