### ISSUE TITLE
Gem install not working

### ISSUE THREAD

**Issue by broccolini** [broccolini/swiss#2]
I'm chatting with the Jekyll folks about this issue but currently it doesn't seem to load the layouts, includes, and sass files when the theme is added as a gem.

**Comment by broccolini** [comment]
It's working, need to improve some setup so that it's easier for people to use though.

**Comment by Alexs7zzh** [comment]
I met this problem. I am pretty sure I have Gemfile and yaml set up correctly. And bundle is fine as well. What should I do?
