### ISSUE TITLE
missing file icon-github.html

### ISSUE THREAD

**Issue by dret** [broccolini/swiss#5]
i followed the instructions given on the site, but when running `bundle exec jekyll serve` got the following error message:

```
Liquid Exception: Could not locate the included file 'icon-github.html' in any of ["/Users/dret/Desktop/github/webdata/_includes", "/Users/dret/.rvm/gems/ruby-2.3.0/gems/jekyll-swiss-0.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source. in about.md
jekyll 3.2.1 | Error:  Could not locate the included file 'icon-github.html' in any of ["/Users/dret/Desktop/github/webdata/_includes", "/Users/dret/.rvm/gems/ruby-2.3.0/gems/jekyll-swiss-0.4.0/_includes"]. Ensure it exists in one of those directories and, if it is a symlink, does not point outside your site source.
```

i am sure i can fix this relatively easily, but wanted to point out that maybe the installation instructions (or procedure) need some fixing.

**Comment by dret** [comment]
seems like i had leftovers from the minima theme i used before (i had to remove the `/css/` directory as well). not sure if the installation instructions should say anything about how to switch. if not, feel free to close this issue.

**Comment by dret** [comment]
or maybe not... ;-) https://github.com/dret/webdata is the repo i am trying to switch to swiss. http://webdata.systems/ is where it's published. i was assuming (or just hoping) that it was just my local jekyll misbehaving, but it seems as if the site now simply is using no theme?

**Comment by dret** [comment]
not quite sure if anybody is reading these issues? it seems that after the switch of https://github.com/dret/webdata (published at http://webdata.systems/) the layout still isn't working. is there any information how to fix the layout after switching from a different one (the site used minima before). thanks!

**Comment by DirtyF** [comment]
Hi @dret, different problems here: 

* GitHub Pages suffers from a bundler buffer right now, so you have to [modify your Gemfile as stated in the issue](https://github.com/github/pages-gem/issues/351#issuecomment-259445262)
* Then you have to run bundle update
* Also you have to use the `home` layout in the homepage
* You have to specify a theme-color in the `_config.yml` file for swiss-theme
* Move the content to posts

I made some quick tests and it runs fine locally, send you a PR 😸

**Comment by dret** [comment]
On 2016-11-11 01:43, Frank Taillandier wrote:
> Hi @dret <https://github.com/dret>, different problems here:
>   * GitHub Pages suffers from a bundler buffer right now, so you have to
>     modify your Gemfile as stated in the issue
>     <https://github.com/github/pages-gem/issues/351#issuecomment-259445262>

that's nasty! thanks for spotting that.

>   * Then you have to run bundle update
>   * Also you have to use the |home| layout in the homepage

that one did not catch my attention. too bad that this does not seem to 
be consistent across themes.

>   * You have to specify a theme-color in the |_config.yml| file for
>     swiss-theme

thanks again for spotting that.

>   * Move the content to posts

well, the idea (for now) is that the content (which is short) actually 
lives on the home page. however, when moving the content to the home 
page, it simply gets ignored.

i switched to jekyll-athena in an effort to make my content visible, but 
that theme seems to ignore home page content as well. is there any 
specific reason for why you cannot have content on your home page, or a 
specific way how to do it?

> I made some quick tests and it runs fine locally, send you a PR 😸

thanks a lot, very much appreciated! i have merged your PR and it 
worked, but i have also tried to recreate the structure that i was 
aiming for (content on home page, posts for updates), but then ran into 
this issue of the home page content being ignored.

**Comment by DirtyF** [comment]
@dret to override the home layout and structure the page as it suits you, see https://jekyllrb.com/docs/themes/#overriding-theme-defaults

**Comment by dret** [comment]
On 2016-11-11 01:43, Frank Taillandier wrote:
>   * Move the content to posts

follow-up: athena not only also ignores home page content, it also 
throws a build error on github for being a non-supported theme. would it 
make sense to switch to themes that are not gem-based, so that they can 
be used with less dependency on github's (lack of) support for themes 
beyond minima?

**Comment by DirtyF** [comment]
Github only supports Minima and jekyll-swiss (see https://pages.github.com/versions/).

To use other gem-based themes on Github, you can [upload your generated site](http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html) on Github, or deploy your website elsewhere, on GitLab Pages or Netlify for instance.

**Comment by dret** [comment]
On 2016-11-11 14:51, Frank Taillandier wrote:
> Github only supports Minima and jekyll-swiss (see
> https://pages.github.com/versions/).

https://pages.github.com/themes/ says: only minima

> To use other gem-based themes on Github, you can upload your generated
> site
> <http://ixti.net/software/2013/01/28/using-jekyll-plugins-on-github-pages.html>
> on Github, or deploy your website elsewhere, on GitLab Pages or Netlify
> for instance.

i might look at that option, thanks. minima is really a bit minimal, and 
jekyll-swiss seems to be very limited in terms of what it supports. i am 
starting to think that i jumped onto the gem-based bandwagon a bit too 
early... ;-)
