### ISSUE TITLE
twitter link not working

### ISSUE THREAD

**Issue by dret** [broccolini/swiss#6]
http://webdata.systems/ uses the swiss theme and the twitter link (the one at the twitter logo) is not working, even though the twitter config is defined (and worked in minima). the repo for the site is at https://github.com/dret/webdata

**Comment by DirtyF** [comment]
@dret [take a look at the default Swiss config.yml file](https://github.com/broccolini/swiss/blob/6b0698e2cdf82d12cf3f84743c46671b1efb8264/_config.yml#L25)

One of the current problem with gem-based themes is that they don't embed a custom config file, so you have to look at the theme's repository config. 🔨

**Comment by dret** [comment]
On 2016-11-11 14:44, Frank Taillandier wrote:
> @dret <https://github.com/dret> take a look at the default Swiss
> config.yml file
> <https://github.com/broccolini/swiss/blob/6b0698e2cdf82d12cf3f84743c46671b1efb8264/_config.yml#L25>
> One of the current problem with gem-based themes is that they don't
> embed a custom config file, so you have to look at the theme's
> repository config. 🔨

hooray, more opaque magic that's different for each theme. my enthusiasm 
for this kind of "everybody does it differently" is not on a steep 
uphill curve.

https://github.com/dret/webdata/commit/177d4d8f6812a2ef7a7615566e5f00aa13ef6332 
fixes things and everything seems to work. thanks again!
